/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_foo_Bar */

#ifndef _Included_com_foo_Bar
#define _Included_com_foo_Bar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_foo_Bar
 * Method:    pong
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_foo_Bar_pong
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
